# Generated by Django 5.0.6 on 2024-07-09 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_acessorio_options_alter_cor_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="acessorio",
            options={"verbose_name": "Acessório", "verbose_name_plural": "Acessórios"},
        ),
    ]
